routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\EquipController;
use App\Http\Controllers\Admin\TicketController;



use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->middleware('can:Ver Panel')->name('index');

// Route::resource('users', UserController::class)->only(['index', 'edit', 'update'])->names('users');

Route::resource('tickets', TicketController::class)->names('tickets');

Route::resource('users', UserController::class)->names('users');

Route::resource('roles', RoleController::class)->names('roles');

Route::resource('departments', DepartmentController::class)->names('departments');

Route::resource('equips', EquipController::class)->names('equips');

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NoticeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HomeController::class)->name('home');

Route::resource('ticket', TicketController::class)->middleware(['auth:sanctum', 'verified'])->names('ticket');
Route::resource('comment', CommentController::class)->middleware(['auth:sanctum', 'verified'])->names('comments');
Route::resource('notice', NoticeController::class)->middleware(['auth:sanctum', 'verified'])->names('notices');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{

    public function __construct()
    {
        $this->middleware('can:Listar Roles')->only('index');
        $this->middleware('can:Crear Roles')->only('create', 'store');
        $this->middleware('can:Editar Roles')->only('edit', 'update');
        $this->middleware('can:Borrar Roles')->only('destroy');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::all();
        return view('admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::all();
        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'permissions' => 'required'
        ]);

        $role = Role::create([
            'name' => $request->name
        ]);

        // Añadimos en la tabla intermedia los permisos de los roles
        $role->permissions()->attach($request->permissions);

        return redirect()->route('admin.roles.index')->with('info', 'El rol se creo satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        return view('admin.roles.show', compact('role'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissions = Permission::all();
        return view('admin.roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $request->validate([
            'name' => 'required',
            'permissions' => 'required'
        ]);


        // actualizamos la tabla intermedia los permisos de los roles
        // Elimina todos los registros y vuelve a cargar los permisos
        $role->permissions()->sync($request->permissions);
        $role->update([
            'name' => $request->name
        ]);

        return redirect()->route('admin.roles.index')->with('info', 'El rol se modificó satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        
        $role->delete();

        return redirect()->route('admin.roles.index')->with('info', 'Eliminado con exito');
    }
}

resources/views/admin/roles/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Crear rol</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'admin.roles.store']) !!}
                <div class="form-group">
                    {!! Form::label('name', 'nombre') !!}
                    {!! Form::text('name', null, ['class' => 'form-control ' . ($errors->has('name') ? 'is-invalid' : ''), 'placeholder' => 'nuevo permiso']) !!}
                    @error('name')
                        <span class="invalid-feedback">
                            Se necesita un nombre.
                        </span>
                    @enderror
                </div>
                <strong>Permisos</strong>
                <br>
                    @error('permissions')
                        <span class="text-danger">
                            Añade al menos un permiso.
                        </span>
                    @enderror
                @foreach ($permissions as $permis)
                <div>

                    {!! Form::checkbox('permissions[]', $permis->id, null, ['class' => 'mr-1']) !!}
                    {{ $permis->name }}
                </div>
                @endforeach
                {!! Form::submit('Crear', ['class' => 'btn btn-primary mt-2']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/roles/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Editar rol</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::model($role, ['route' => ['admin.roles.update', $role], 'method' => 'put']) !!}
                <div class="form-group">
                    {!! Form::label('name', 'nombre') !!}
                    {!! Form::text('name', null, ['class' => 'form-control ' . ($errors->has('name') ? 'is-invalid' : '')]) !!}
                    @error('name')
                        <span class="invalid-feedback">
                            Se necesita un nombre.
                        </span>
                    @enderror
                </div>
                <strong>Permisos</strong>
                <br>

                @error('permissions')
                    <span class="text-danger">
                        Añade al menos un permiso.
                    </span>
                @enderror

                @foreach ($permissions as $permis)
                <div>
                    {!! Form::checkbox('permissions[]', $permis->id, null, ['class' => 'mr-1']) !!}
                    {{ $permis->name }}
                </div>
                @endforeach
                {!! Form::submit('Editar', ['class' => 'btn btn-primary mt-2']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

resources/views/admin/roles/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')

@stop

@section('content')
<a href="{{ route('admin.roles.create') }}"><button class="btn btn-outline-dark mb-3">Nuevo Rol</button></a>

    @if (session('info'))
        <div class="alert alert-primary" role="alert">
            <strong>Éxito!</strong> {{ session('info') }}
        </div>

    @endif

    <table class="table table-striped">
        <thead>
            <tr class="bg-primary">
                <th  scope="col">id</th>
                <th  scope="col">nombre</th>
                <th  scope="col">Editar</th>
                <th  scope="col">Eliminar</th>
                <th  scope="col">Permisos</th>

            </tr>
        </thead>
        <tbody>
            @forelse ($roles as $role)
                <tr>
                    <td>{{ $role->id }}</td>
                    <td>{{ $role->name }}</td>
                    <td>
                        <a href="{{ route('admin.roles.edit', $role) }}"><button class="btn btn-info">
                            <i class="fas fa-edit"></i>
                        </button></a>
                    </td>
                    <td>
                        <form action="{{ route('admin.roles.destroy', $role) }}" method="POST">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger" type="submit" onclick="return confirm('Está seguro?')"><i class="fas fa-trash-alt "></i></button>
                        </form>
                    </td>
                    <td>
                        @foreach ($role->permissions as $permission)
                            {{ $permission->name }},
                        @endforeach
                    </td>
                </tr>
            @empty
                <tr>
                    <td>No hay ningún rol.</td>
                </tr>
            @endforelse

        </tbody>
    </table>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop