routes/admin.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\EquipController;
use App\Http\Controllers\Admin\TicketController;



use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->middleware('can:Ver Panel')->name('index');

// Route::resource('users', UserController::class)->only(['index', 'edit', 'update'])->names('users');

Route::resource('tickets', TicketController::class)->names('tickets');

Route::resource('users', UserController::class)->names('users');

Route::resource('roles', RoleController::class)->names('roles');

Route::resource('departments', DepartmentController::class)->names('departments');

Route::resource('equips', EquipController::class)->names('equips');

routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\NoticeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', HomeController::class)->name('home');

Route::resource('ticket', TicketController::class)->middleware(['auth:sanctum', 'verified'])->names('ticket');
Route::resource('comment', CommentController::class)->middleware(['auth:sanctum', 'verified'])->names('comments');
Route::resource('notice', NoticeController::class)->middleware(['auth:sanctum', 'verified'])->names('notices');



Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/AdminEquips.php
<?php

namespace App\Http\Livewire;

use App\Models\Equip;
use Livewire\Component;

use Livewire\WithPagination;

class AdminEquips extends Component
{
    use WithPagination;

    protected $paginationTheme = "bootstrap";

    public $search;

    public function render()
    {
        $equips = Equip::where('mac', 'LIKE', '%' . $this->search . '%')
            ->orWhere('serie', 'LIKE', '%' . $this->search . '%')
            ->orWhere('ip', 'LIKE', '%' . $this->search . '%')
            ->paginate(8);

        return view('livewire.admin-equips', compact('equips'));
    }

    // Para que al buscar con el buscador, busque en cualquier pagina necesitamos resetear page
    public function limpiarPaginate(){
        $this->reset('page');
    }
}

app/Http/Livewire/AdminTicket.php
<?php

namespace App\Http\Livewire;

use App\Models\State;
use App\Models\Ticket;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;

use Livewire\WithPagination;


class AdminTicket extends Component
{

    use WithPagination;

    protected $paginationTheme = "bootstrap";

    public $search;

    public function render()
    {

        $tickets = Ticket::where('subject', 'LIKE', '%' . $this->search . '%')
        ->orderBy('updated_at', 'desc')->paginate(8);
        $states = State::all();

        return view('livewire.admin-ticket', compact('tickets', 'states'));
    }

    // Para que al buscar con el buscador, busque en cualquier pagina necesitamos resetear page
    public function limpiarPaginate(){
        $this->reset('page');
    }
}

app/Http/Livewire/AdminUsers.php
<?php

namespace App\Http\Livewire;

use App\Models\User;
use Livewire\Component;

use Livewire\WithPagination;

class AdminUsers extends Component
{
    use WithPagination;

    protected $paginationTheme = "bootstrap";

    public $search;

    public function render()
    {
        $users = User::where('name', 'LIKE', '%' . $this->search . '%')
            ->orWhere('email', 'LIKE', '%' . $this->search . '%')
            ->paginate(8);

        return view('livewire.admin-users', compact('users'));
    }

    // Para que al buscar con el buscador, busque en cualquier pagina necesitamos resetear page
    public function limpiarPaginate(){
        $this->reset('page');
    }
}

app/Http/Livewire/CardNotices.php
<?php

namespace App\Http\Livewire;

use App\Models\Notice;
use Livewire\Component;

class CardNotices extends Component
{
    public $notice;


    public function mount(Notice $notice){
        $this->notice = $notice;
    }

    public function render()
    {
        return view('livewire.card-notices');
    }
}

app/Http/Livewire/CardTicket.php
<?php

namespace App\Http\Livewire;

use App\Models\State;
use App\Models\Ticket;
use Livewire\Component;

class CardTicket extends Component

{

    public $ticket;
    public $states;

    public function mount(Ticket $ticket){
        $this->ticket = $ticket;
        $this->states = State::orderBy('name')->pluck('name', 'id');
    }

    public function render()
    {
        return view('livewire.card-ticket');
    }
}

app/Http/Livewire/TicketStatus.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class TicketStatus extends Component
{
    public $comments;
    public $ticket;

    public function render()
    {
        return view('livewire.ticket-status');
    }

    public function mount($comments, $ticket){
        $this->comments = $comments;
        $this->ticket = $ticket;
    }
}

resources/views/livewire/admin-equips.blade.php
<div>
    <a href="{{ route('admin.equips.create') }}"><button class="btn btn-outline-dark mb-3">Nuevo Equipo</button></a>

    <div class="card">
        <input wire:keydown="limpiarPaginate" wire:model="search" class="form-control" type="text" placeholder="Buscar" >
    </div>
    @if (session('info'))
        <div class="alert alert-primary" role="alert">
            <strong>Éxito!</strong> {{ session('info') }}
        </div>
    @endif
        <table class="table table-striped">
            <thead>
                <tr class="bg-primary">
                    <th scope="col">Serie</th>
                    <th scope="col">MAC</th>
                    <th scope="col">IP</th>
                    <th scope="col">Marca</th>
                    <th scope="col">Departamento</th>
                    <th scope="col">Editar</th>
                    <th scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($equips as $equip)
                    <tr>
                        <th scope="row">{{ $equip->serie }}</td>
                        <td  >{{ $equip->mac }}</td>
                        <td  >{{ $equip->ip }}</td>
                        <td  >{{ $equip->brand->name }}</td>
                        <td  >{{ $equip->department->name }}</td>
                        <td  >
                            <a href="{{ route('admin.equips.edit', $equip) }}"><button class="btn btn-info">
                                <i class="fas fa-edit"></i>
                            </button></a>
                        </td>
                        <td  >
                            <form action="{{ route('admin.equips.destroy', $equip) }}" method="POST">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" type="submit" onclick="return confirm('Estas seguro?')"><i class="fas fa-trash-alt "></i></button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td>No hay ningún equipo.</td>
                    </tr>
                @endforelse

            </tbody>
        </table>
        <div class="card-footer">
            {{ $equips->links() }}
        </div>

</div>

resources/views/livewire/admin-ticket.blade.php
<div>
    <a  href="{{ route('ticket.create') }}"><button class="btn btn-outline-dark mb-3">Nuevo Ticket</button></a>

    <div class="card">
        <input wire:keydown="limpiarPaginate" wire:model="search" class="form-control" type="text" placeholder="Buscar" >
    </div>
    @if (session('info'))
        <div class="alert alert-primary" role="alert">
            <strong>Éxito!</strong> {{ session('info') }}
        </div>
    @endif
    <div class="card">
        @if ($tickets->count())

        <table class="table table-striped">
        <thead>
            <tr class="bg-primary">
                <th  scope="col">Asunto</th>
                <th  scope="col">Equipo</th>
                <th  scope="col">Departamento</th>
                <th  scope="col">Estado</th>
                <th  scope="col">Eliminado</th>
                <th  scope="col">Eliminar</th>

            </tr>
        </thead>
        <tbody>
            @forelse ($tickets as $ticket)
                <tr>
                    <td class="font-weight-bold"><a href="{{ route('ticket.show', $ticket) }}">{{ Str::limit($ticket->subject, 50, '...') }}</a></td>
                    <td class="font-weight-bold">{{ isset($ticket->equip) ? $ticket->equip->brand->model : '...' }}</td>
                    <td class="font-weight-bold">{{ isset($ticket->department) ? $ticket->department->name : '' }}</td>
                    <td class="font-weight-bold">{{ isset($ticket->state) ? $ticket->state->name : 'Null' }}</td>
                    <td class="font-weight-bold text-center">
                    @if ($ticket->deleted)
                    <i class="fas fa-ban" style="color:#ff0000;"></i>
                    @endif
                    </td>
                    <td class="font-weight-bold">
                        <form action="{{ route('admin.tickets.destroy', $ticket) }}" method="POST">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger" type="submit" onclick="return confirm('Está seguro?')"><i class="fas fa-trash-alt "></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                    <tr>
                        <td>No hay ningún ticket.</td>
                    </tr>
                @endforelse

            </tbody>
        </table>
    </div>
    <div class="card-footer">
        {{ $tickets->links() }}
    </div>
    @else
    <div class="card-body">
        <strong>No hay registros</strong>
    </div>
    @endif
</div>

resources/views/livewire/admin-users.blade.php
<div>
    <a  href="{{ route('admin.users.create') }}"><button class="btn btn-outline-dark mb-3">Nuevo Usuario</button></a>

    <div class="card">
        <input wire:keydown="limpiarPaginate" wire:model="search" class="form-control" type="text" placeholder="Buscar" >
    </div>
    @if (session('info'))
        <div class="alert alert-primary" role="alert">
            <strong>Éxito!</strong> {{ session('info') }}
        </div>
    @endif
    <div class="card">
        @if ($users->count())
            <table class="table table-striped">
            <thead>
                <tr class="bg-primary">
                    <th  scope="col">nombre</th>
                    <th  scope="col">email</th>
                    <th  scope="col">unidad</th>
                    <th  scope="col">Editar</th>
                    <th  scope="col">Eliminar</th>
                    <th  scope="col">Roles</th>

                </tr>
            </thead>
            <tbody>
                @forelse ($users as $user)
                    <tr class="">
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ isset($user->department) ? $user->department->name : '' }}</td>
                        <td>
                            <a href="{{ route('admin.users.edit', $user) }}"><button class="btn btn-info">
                                <i class="fas fa-edit"></i>
                            </button></a>
                        </td>
                        <td>
                            <form action="{{ route('admin.users.destroy', $user) }}" method="POST">
                                @csrf
                                @method('delete')
                                <button class="btn btn-danger" type="submit" onclick="return confirm('Está seguro?')"><i class="fas fa-trash-alt "></i></button>
                            </form>
                        </td>
                        <td>
                            @forelse ($user->roles as $rol)
                                - {{ $rol->name }}
                            @empty
                                Sin rol asignado
                            @endforelse
                        </td>
                    </tr>
                @empty
                        <tr>
                            <td>No hay ningún usuario.</td>
                        </tr>
                    @endforelse

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{ $users->links() }}
        </div>
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>
</div>

resources/views/livewire/card-notices.blade.php
<div>
    <div class="bg-gray-100 rounded-lg shadow-md mb-5 grid grid-cols-3 gap-4">

        <div class="mt-2 px-3 col-span-2">
            <p class="text-2xl text-gray-800 font-extrabold" >{{$notice->title}}</p>
        </div>
        
        @can('Editar Novedades')
            <div class="text-right mr-3">
                <a href="{{ route('notices.edit', $notice) }}"><button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
                    Editar
                </button></a>
            </div>
        @endcan


        <div class="col-span-3">
            <div class="p-3 mx-3 rounded-md bg-gray-200 font-bold grid grid-cols-2">
                <div>
                    <p>Creado: <span class="font-light">{{ $notice->created_at }}</span></p>
                </div>
                <div>
                    <p> Autor: <span class="font-light">{{ $notice->user_id  ? $notice->user->name : ''  }}</span></p>
                </div>
            </div>
        </div>

        <div class="col-span-2 px-3 mb-5">
            <p class="mt-2 text-gray-800 font-semibold">{!! $notice->body !!}</p>
        </div>
        <div class="text-right  mr-3">
            @can('Borrar Novedades')
                <form action="{{ route('notices.destroy', $notice) }}" method="POST">
                    @csrf
                    @method('delete')
                    <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" type="submit" onclick="return confirm('Estas seguro?')">Eliminar</button>
                </form>
            @endcan

        </div>

    </div>
</div>

resources/views/livewire/card-ticket.blade.php
<div>
    <div class="bg-white bg-gradient-to-b from-gray-100 rounded-lg shadow-md mb-5 grid grid-cols-3 gap-4">

        <div class="mt-2 px-3 col-span-2">
            <a href="{{ route('ticket.show', [$ticket->id]) }}" class="text-2xl text-gray-800 font-extrabold" >{{$ticket->subject}}</a>
        </div>
        <div class="text-right mr-3">
            {{ Form::model($ticket, array('route' => array('ticket.update', $ticket->id), 'method' => 'PUT')) }}
                @csrf
                {!! Form::select('state_id', $states, $ticket->state_id, ['class' => 'bg-gray-200 hover:bg-gray-400 font-bold py-2 px-4 rounded']) !!}
                {!! Form::submit('Cambiar estado', ['class' => 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded']) !!}
            {!! Form::close() !!}

        </div>
        <div class="col-span-3">
            <div class="p-3 mx-3 rounded-md bg-gray-200 font-bold grid grid-cols-2">
                <div>
                    <p>Estado: <span class="font-light">{{ $ticket->state_id ? $ticket->state->name : '' }}</span></p>
                    <p>Creado: <span class="font-light">{{ $ticket->created_at }}</span></p>
                    <p>Actulaizado: <span class="font-light">{{ $ticket->updated_at }}</span></p>
                </div>
                <div>
                    <p> Creado por: <span class="font-light">{{ $ticket->department_id  ? $ticket->department->name : ''  }}</span></p>
                    <p> Equipo: <span class="font-light"> {{ $ticket->equip_id  ? $ticket->equip->brand->name : ''  }}</span></p>
                    <p> Nº Serie: <span class="font-light"> {{ $ticket->equip_id  ? $ticket->equip->serie : '' }}</span></p>
                </div>
            </div>
        </div>
        <div class="col-span-2 px-3 mb-5">
            <p class="mt-2 text-gray-800 font-semibold">{!! $ticket->body !!}</p>
        </div>
        <div class="text-right mr-3">
            <form action="{{ route('ticket.destroy', $ticket) }}" method="POST">
                @csrf
                @method('delete')
                <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" type="submit" onclick="return confirm('Estas seguro?')">Eliminar</button>
            </form> 
        </div>

    </div>
</div>

resources/views/livewire/tech-admin.blade.php
<div>
    {{-- In work, do what you enjoy. --}}
</div>

resources/views/livewire/ticket-estados.blade.php
<div>
            {{-- Menu --}}

    <x-tickets-submenu :states="$states" />


                    {{-- seccion principal --}}
    <section class="mt-10 max-w-7xl mx-auto px-4 sm:px-6 ">
        <h1 class="text-gray-700 text-center text-4xl font-bold mb-6">Tickets</h1>

        <div>
            @foreach ($tickets as $ticket)
            <x-card-ticket>
                <x-slot name="title">
                    {{ $ticket->asunto }}
                </x-slot>
                <x-slot name="unit">
                    {{ $ticket->unit->nombre }}
                </x-slot>
                <x-slot name="date">
                    {{ $ticket->updated_at->format('d M yy H:m') }}
                </x-slot>
                <x-slot name="icon">
                    {{ asset('img/icons/camping.png') }}
                </x-slot>
                <x-slot name="ticket_id">
                    {{ $ticket->id }}
                </x-slot>
                <x-slot name="state">
                    {{ $ticket->state->nombre }}
                </x-slot>
                {{ $ticket->cuerpo }}
            </x-post>
            @endforeach
        </div>
        <div class="mb-2">
            {{ $tickets->links() }}
        </div>
    </section>
</div>

resources/views/livewire/ticket-status.blade.php
<div>
    <h3 class="text-gray-700 text-center text-2xl font-bold mb-6">Comentarios</h3>
        @foreach ($comments as $comment)

            <x-card-comment>
                <x-slot name="unit">
                    {{ $comment->user->name }}
                </x-slot>
                <x-slot name="date">
                    {{ $comment->created_at->format('d M yy H:m') }}
                </x-slot>
                <x-slot name="icon">
                    {{ asset('img/icons/camping.png') }}
                </x-slot>

                {!! $comment->body !!}
            </x-card-comment>

        @endforeach

        <div class="mt-4 bg-white bg-gradient-to-b from-gray-200 shadow-md gap-4">
        <p class="text-gray-800 text-center font-bold mb-1"><span class="text-lg">Nuevo comentario</span></p>
            {!! Form::open(['route' => 'comments.store']) !!}
                @csrf
                {!! Form::hidden('ticket_id', $ticket->id) !!}
                {!! Form::textarea("body") !!}

                <script>CKEDITOR.replace( 'body' );</script>

                {!! Form::submit('Enviar', ['class' => 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded']) !!}
            {!! Form::close() !!}
        </div>
</div>